name: sirochat
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  firebase_storage: ^10.2.18
  flutter_local_notifications: ^9.5.3
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  google_sign_in: ^5.3.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  photo_view: ^0.14.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/